<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://bankA.sample.ibm.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="AccountServicing" targetNamespace="http://bankA.sample.ibm.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://bankA.sample.ibm.com/" elementFormDefault="unqualified" targetNamespace="http://bankA.sample.ibm.com/" version="1.0">
<xs:element name="getBalance" type="tns:getBalance"></xs:element>
<xs:element name="getBalanceResponse" type="tns:getBalanceResponse"></xs:element>
<xs:complexType name="getBalance">
    <xs:sequence>
      <xs:element name="arg0" type="xs:int"></xs:element>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="getBalanceResponse">
    <xs:sequence>
      <xs:element name="return" type="xs:int"></xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>  </wsdl:types>
  <wsdl:message name="getBalanceResponse">
    <wsdl:part element="tns:getBalanceResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getBalance">
    <wsdl:part element="tns:getBalance" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Account">
    <wsdl:operation name="getBalance">
      <wsdl:input message="tns:getBalance" name="getBalance">
    </wsdl:input>
      <wsdl:output message="tns:getBalanceResponse" name="getBalanceResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AccountServicingSoapBinding" type="tns:Account">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
    <wsdl:operation name="getBalance">
      <soap:operation soapAction="getBalance" style="document"></soap:operation>
      <wsdl:input name="getBalance">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="getBalanceResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AccountServicing">
    <wsdl:port binding="tns:AccountServicingSoapBinding" name="AccountPort">
      <soap:address location="https://apictutorials.mybluemix.net/AccountService"></soap:address>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>